// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.mm.account.proto;

public final class Account {
  private Account() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.mm.account.proto.Gender}
   */
  public enum Gender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MALE = 1;</code>
     */
    MALE(0, 1),
    /**
     * <code>FEMALE = 2;</code>
     */
    FEMALE(1, 2),
    ;

    /**
     * <code>MALE = 1;</code>
     */
    public static final int MALE_VALUE = 1;
    /**
     * <code>FEMALE = 2;</code>
     */
    public static final int FEMALE_VALUE = 2;


    public final int getNumber() { return value; }

    public static Gender valueOf(int value) {
      switch (value) {
        case 1: return MALE;
        case 2: return FEMALE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.mm.account.proto.Account.getDescriptor().getEnumTypes().get(0);
    }

    private static final Gender[] VALUES = values();

    public static Gender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Gender(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.mm.account.proto.Gender)
  }

  /**
   * Protobuf enum {@code com.mm.account.proto.DeviceType}
   */
  public enum DeviceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ANDROID = 1;</code>
     */
    ANDROID(0, 1),
    /**
     * <code>IOS = 2;</code>
     */
    IOS(1, 2),
    ;

    /**
     * <code>ANDROID = 1;</code>
     */
    public static final int ANDROID_VALUE = 1;
    /**
     * <code>IOS = 2;</code>
     */
    public static final int IOS_VALUE = 2;


    public final int getNumber() { return value; }

    public static DeviceType valueOf(int value) {
      switch (value) {
        case 1: return ANDROID;
        case 2: return IOS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DeviceType>() {
            public DeviceType findValueByNumber(int number) {
              return DeviceType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.mm.account.proto.Account.getDescriptor().getEnumTypes().get(1);
    }

    private static final DeviceType[] VALUES = values();

    public static DeviceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private DeviceType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.mm.account.proto.DeviceType)
  }

  public interface AccountUserInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 version = 1;
    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    // required int32 uid = 2;
    /**
     * <code>required int32 uid = 2;</code>
     */
    boolean hasUid();
    /**
     * <code>required int32 uid = 2;</code>
     */
    int getUid();

    // optional .com.mm.account.proto.Gender gender = 3;
    /**
     * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
     */
    boolean hasGender();
    /**
     * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
     */
    com.mm.account.proto.Account.Gender getGender();

    // optional string first_name = 4;
    /**
     * <code>optional string first_name = 4;</code>
     */
    boolean hasFirstName();
    /**
     * <code>optional string first_name = 4;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>optional string first_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    // optional string last_name = 5;
    /**
     * <code>optional string last_name = 5;</code>
     */
    boolean hasLastName();
    /**
     * <code>optional string last_name = 5;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>optional string last_name = 5;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();
  }
  /**
   * Protobuf type {@code com.mm.account.proto.AccountUserInfo}
   */
  public static final class AccountUserInfo extends
      com.google.protobuf.GeneratedMessage
      implements AccountUserInfoOrBuilder {
    // Use AccountUserInfo.newBuilder() to construct.
    private AccountUserInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AccountUserInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AccountUserInfo defaultInstance;
    public static AccountUserInfo getDefaultInstance() {
      return defaultInstance;
    }

    public AccountUserInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AccountUserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              uid_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.mm.account.proto.Account.Gender value = com.mm.account.proto.Account.Gender.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                gender_ = value;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              firstName_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              lastName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mm.account.proto.Account.internal_static_com_mm_account_proto_AccountUserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mm.account.proto.Account.internal_static_com_mm_account_proto_AccountUserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mm.account.proto.Account.AccountUserInfo.class, com.mm.account.proto.Account.AccountUserInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<AccountUserInfo> PARSER =
        new com.google.protobuf.AbstractParser<AccountUserInfo>() {
      public AccountUserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccountUserInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AccountUserInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    // required int32 uid = 2;
    public static final int UID_FIELD_NUMBER = 2;
    private int uid_;
    /**
     * <code>required int32 uid = 2;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 uid = 2;</code>
     */
    public int getUid() {
      return uid_;
    }

    // optional .com.mm.account.proto.Gender gender = 3;
    public static final int GENDER_FIELD_NUMBER = 3;
    private com.mm.account.proto.Account.Gender gender_;
    /**
     * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
     */
    public boolean hasGender() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
     */
    public com.mm.account.proto.Account.Gender getGender() {
      return gender_;
    }

    // optional string first_name = 4;
    public static final int FIRST_NAME_FIELD_NUMBER = 4;
    private java.lang.Object firstName_;
    /**
     * <code>optional string first_name = 4;</code>
     */
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string first_name = 4;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string first_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string last_name = 5;
    public static final int LAST_NAME_FIELD_NUMBER = 5;
    private java.lang.Object lastName_;
    /**
     * <code>optional string last_name = 5;</code>
     */
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string last_name = 5;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string last_name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      version_ = 0;
      uid_ = 0;
      gender_ = com.mm.account.proto.Account.Gender.MALE;
      firstName_ = "";
      lastName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, uid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, gender_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getLastNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, uid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, gender_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getLastNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mm.account.proto.Account.AccountUserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mm.account.proto.Account.AccountUserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mm.account.proto.Account.AccountUserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mm.account.proto.Account.AccountUserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mm.account.proto.Account.AccountUserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mm.account.proto.Account.AccountUserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mm.account.proto.Account.AccountUserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mm.account.proto.Account.AccountUserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mm.account.proto.Account.AccountUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mm.account.proto.Account.AccountUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mm.account.proto.Account.AccountUserInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mm.account.proto.AccountUserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mm.account.proto.Account.AccountUserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mm.account.proto.Account.internal_static_com_mm_account_proto_AccountUserInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mm.account.proto.Account.internal_static_com_mm_account_proto_AccountUserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mm.account.proto.Account.AccountUserInfo.class, com.mm.account.proto.Account.AccountUserInfo.Builder.class);
      }

      // Construct using com.mm.account.proto.Account.AccountUserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        gender_ = com.mm.account.proto.Account.Gender.MALE;
        bitField0_ = (bitField0_ & ~0x00000004);
        firstName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        lastName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mm.account.proto.Account.internal_static_com_mm_account_proto_AccountUserInfo_descriptor;
      }

      public com.mm.account.proto.Account.AccountUserInfo getDefaultInstanceForType() {
        return com.mm.account.proto.Account.AccountUserInfo.getDefaultInstance();
      }

      public com.mm.account.proto.Account.AccountUserInfo build() {
        com.mm.account.proto.Account.AccountUserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mm.account.proto.Account.AccountUserInfo buildPartial() {
        com.mm.account.proto.Account.AccountUserInfo result = new com.mm.account.proto.Account.AccountUserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gender_ = gender_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.firstName_ = firstName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.lastName_ = lastName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mm.account.proto.Account.AccountUserInfo) {
          return mergeFrom((com.mm.account.proto.Account.AccountUserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mm.account.proto.Account.AccountUserInfo other) {
        if (other == com.mm.account.proto.Account.AccountUserInfo.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasGender()) {
          setGender(other.getGender());
        }
        if (other.hasFirstName()) {
          bitField0_ |= 0x00000008;
          firstName_ = other.firstName_;
          onChanged();
        }
        if (other.hasLastName()) {
          bitField0_ |= 0x00000010;
          lastName_ = other.lastName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasUid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mm.account.proto.Account.AccountUserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mm.account.proto.Account.AccountUserInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 version = 1;
      private int version_ ;
      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      // required int32 uid = 2;
      private int uid_ ;
      /**
       * <code>required int32 uid = 2;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 uid = 2;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>required int32 uid = 2;</code>
       */
      public Builder setUid(int value) {
        bitField0_ |= 0x00000002;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 uid = 2;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uid_ = 0;
        onChanged();
        return this;
      }

      // optional .com.mm.account.proto.Gender gender = 3;
      private com.mm.account.proto.Account.Gender gender_ = com.mm.account.proto.Account.Gender.MALE;
      /**
       * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
       */
      public boolean hasGender() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
       */
      public com.mm.account.proto.Account.Gender getGender() {
        return gender_;
      }
      /**
       * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
       */
      public Builder setGender(com.mm.account.proto.Account.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gender_ = com.mm.account.proto.Account.Gender.MALE;
        onChanged();
        return this;
      }

      // optional string first_name = 4;
      private java.lang.Object firstName_ = "";
      /**
       * <code>optional string first_name = 4;</code>
       */
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string first_name = 4;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string first_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string first_name = 4;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string first_name = 4;</code>
       */
      public Builder clearFirstName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string first_name = 4;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        firstName_ = value;
        onChanged();
        return this;
      }

      // optional string last_name = 5;
      private java.lang.Object lastName_ = "";
      /**
       * <code>optional string last_name = 5;</code>
       */
      public boolean hasLastName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string last_name = 5;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string last_name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string last_name = 5;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string last_name = 5;</code>
       */
      public Builder clearLastName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string last_name = 5;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        lastName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mm.account.proto.AccountUserInfo)
    }

    static {
      defaultInstance = new AccountUserInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mm.account.proto.AccountUserInfo)
  }

  public interface AccountPhoneInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 uid = 1;
    /**
     * <code>required int32 uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required int32 uid = 1;</code>
     */
    int getUid();

    // required int32 phone_num = 2;
    /**
     * <code>required int32 phone_num = 2;</code>
     */
    boolean hasPhoneNum();
    /**
     * <code>required int32 phone_num = 2;</code>
     */
    int getPhoneNum();

    // optional string imei = 3;
    /**
     * <code>optional string imei = 3;</code>
     */
    boolean hasImei();
    /**
     * <code>optional string imei = 3;</code>
     */
    java.lang.String getImei();
    /**
     * <code>optional string imei = 3;</code>
     */
    com.google.protobuf.ByteString
        getImeiBytes();

    // optional string device_id = 4;
    /**
     * <code>optional string device_id = 4;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>optional string device_id = 4;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>optional string device_id = 4;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    // optional .com.mm.account.proto.DeviceType device_type = 5;
    /**
     * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
     */
    boolean hasDeviceType();
    /**
     * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
     */
    com.mm.account.proto.Account.DeviceType getDeviceType();
  }
  /**
   * Protobuf type {@code com.mm.account.proto.AccountPhoneInfo}
   */
  public static final class AccountPhoneInfo extends
      com.google.protobuf.GeneratedMessage
      implements AccountPhoneInfoOrBuilder {
    // Use AccountPhoneInfo.newBuilder() to construct.
    private AccountPhoneInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AccountPhoneInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AccountPhoneInfo defaultInstance;
    public static AccountPhoneInfo getDefaultInstance() {
      return defaultInstance;
    }

    public AccountPhoneInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AccountPhoneInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              phoneNum_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              imei_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              deviceId_ = input.readBytes();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.mm.account.proto.Account.DeviceType value = com.mm.account.proto.Account.DeviceType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                deviceType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mm.account.proto.Account.internal_static_com_mm_account_proto_AccountPhoneInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mm.account.proto.Account.internal_static_com_mm_account_proto_AccountPhoneInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mm.account.proto.Account.AccountPhoneInfo.class, com.mm.account.proto.Account.AccountPhoneInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<AccountPhoneInfo> PARSER =
        new com.google.protobuf.AbstractParser<AccountPhoneInfo>() {
      public AccountPhoneInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccountPhoneInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AccountPhoneInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 uid = 1;
    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>required int32 uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }

    // required int32 phone_num = 2;
    public static final int PHONE_NUM_FIELD_NUMBER = 2;
    private int phoneNum_;
    /**
     * <code>required int32 phone_num = 2;</code>
     */
    public boolean hasPhoneNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 phone_num = 2;</code>
     */
    public int getPhoneNum() {
      return phoneNum_;
    }

    // optional string imei = 3;
    public static final int IMEI_FIELD_NUMBER = 3;
    private java.lang.Object imei_;
    /**
     * <code>optional string imei = 3;</code>
     */
    public boolean hasImei() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string imei = 3;</code>
     */
    public java.lang.String getImei() {
      java.lang.Object ref = imei_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imei_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string imei = 3;</code>
     */
    public com.google.protobuf.ByteString
        getImeiBytes() {
      java.lang.Object ref = imei_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string device_id = 4;
    public static final int DEVICE_ID_FIELD_NUMBER = 4;
    private java.lang.Object deviceId_;
    /**
     * <code>optional string device_id = 4;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string device_id = 4;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string device_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .com.mm.account.proto.DeviceType device_type = 5;
    public static final int DEVICE_TYPE_FIELD_NUMBER = 5;
    private com.mm.account.proto.Account.DeviceType deviceType_;
    /**
     * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
     */
    public boolean hasDeviceType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
     */
    public com.mm.account.proto.Account.DeviceType getDeviceType() {
      return deviceType_;
    }

    private void initFields() {
      uid_ = 0;
      phoneNum_ = 0;
      imei_ = "";
      deviceId_ = "";
      deviceType_ = com.mm.account.proto.Account.DeviceType.ANDROID;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPhoneNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, phoneNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getImeiBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, deviceType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, phoneNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getImeiBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, deviceType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mm.account.proto.Account.AccountPhoneInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mm.account.proto.Account.AccountPhoneInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mm.account.proto.Account.AccountPhoneInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mm.account.proto.Account.AccountPhoneInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mm.account.proto.Account.AccountPhoneInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mm.account.proto.Account.AccountPhoneInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mm.account.proto.Account.AccountPhoneInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mm.account.proto.Account.AccountPhoneInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mm.account.proto.Account.AccountPhoneInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mm.account.proto.Account.AccountPhoneInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mm.account.proto.Account.AccountPhoneInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mm.account.proto.AccountPhoneInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mm.account.proto.Account.AccountPhoneInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mm.account.proto.Account.internal_static_com_mm_account_proto_AccountPhoneInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mm.account.proto.Account.internal_static_com_mm_account_proto_AccountPhoneInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mm.account.proto.Account.AccountPhoneInfo.class, com.mm.account.proto.Account.AccountPhoneInfo.Builder.class);
      }

      // Construct using com.mm.account.proto.Account.AccountPhoneInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        phoneNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        imei_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceType_ = com.mm.account.proto.Account.DeviceType.ANDROID;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mm.account.proto.Account.internal_static_com_mm_account_proto_AccountPhoneInfo_descriptor;
      }

      public com.mm.account.proto.Account.AccountPhoneInfo getDefaultInstanceForType() {
        return com.mm.account.proto.Account.AccountPhoneInfo.getDefaultInstance();
      }

      public com.mm.account.proto.Account.AccountPhoneInfo build() {
        com.mm.account.proto.Account.AccountPhoneInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mm.account.proto.Account.AccountPhoneInfo buildPartial() {
        com.mm.account.proto.Account.AccountPhoneInfo result = new com.mm.account.proto.Account.AccountPhoneInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.phoneNum_ = phoneNum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.imei_ = imei_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.deviceType_ = deviceType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mm.account.proto.Account.AccountPhoneInfo) {
          return mergeFrom((com.mm.account.proto.Account.AccountPhoneInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mm.account.proto.Account.AccountPhoneInfo other) {
        if (other == com.mm.account.proto.Account.AccountPhoneInfo.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasPhoneNum()) {
          setPhoneNum(other.getPhoneNum());
        }
        if (other.hasImei()) {
          bitField0_ |= 0x00000004;
          imei_ = other.imei_;
          onChanged();
        }
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000008;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasDeviceType()) {
          setDeviceType(other.getDeviceType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        if (!hasPhoneNum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mm.account.proto.Account.AccountPhoneInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mm.account.proto.Account.AccountPhoneInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 uid = 1;
      private int uid_ ;
      /**
       * <code>required int32 uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 uid = 1;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>required int32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0;
        onChanged();
        return this;
      }

      // required int32 phone_num = 2;
      private int phoneNum_ ;
      /**
       * <code>required int32 phone_num = 2;</code>
       */
      public boolean hasPhoneNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 phone_num = 2;</code>
       */
      public int getPhoneNum() {
        return phoneNum_;
      }
      /**
       * <code>required int32 phone_num = 2;</code>
       */
      public Builder setPhoneNum(int value) {
        bitField0_ |= 0x00000002;
        phoneNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 phone_num = 2;</code>
       */
      public Builder clearPhoneNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        phoneNum_ = 0;
        onChanged();
        return this;
      }

      // optional string imei = 3;
      private java.lang.Object imei_ = "";
      /**
       * <code>optional string imei = 3;</code>
       */
      public boolean hasImei() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string imei = 3;</code>
       */
      public java.lang.String getImei() {
        java.lang.Object ref = imei_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          imei_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string imei = 3;</code>
       */
      public com.google.protobuf.ByteString
          getImeiBytes() {
        java.lang.Object ref = imei_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imei_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string imei = 3;</code>
       */
      public Builder setImei(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        imei_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string imei = 3;</code>
       */
      public Builder clearImei() {
        bitField0_ = (bitField0_ & ~0x00000004);
        imei_ = getDefaultInstance().getImei();
        onChanged();
        return this;
      }
      /**
       * <code>optional string imei = 3;</code>
       */
      public Builder setImeiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        imei_ = value;
        onChanged();
        return this;
      }

      // optional string device_id = 4;
      private java.lang.Object deviceId_ = "";
      /**
       * <code>optional string device_id = 4;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string device_id = 4;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_id = 4;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_id = 4;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_id = 4;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceId_ = value;
        onChanged();
        return this;
      }

      // optional .com.mm.account.proto.DeviceType device_type = 5;
      private com.mm.account.proto.Account.DeviceType deviceType_ = com.mm.account.proto.Account.DeviceType.ANDROID;
      /**
       * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
       */
      public boolean hasDeviceType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
       */
      public com.mm.account.proto.Account.DeviceType getDeviceType() {
        return deviceType_;
      }
      /**
       * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
       */
      public Builder setDeviceType(com.mm.account.proto.Account.DeviceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
       */
      public Builder clearDeviceType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        deviceType_ = com.mm.account.proto.Account.DeviceType.ANDROID;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mm.account.proto.AccountPhoneInfo)
    }

    static {
      defaultInstance = new AccountPhoneInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mm.account.proto.AccountPhoneInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mm_account_proto_AccountUserInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mm_account_proto_AccountUserInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mm_account_proto_AccountPhoneInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mm_account_proto_AccountPhoneInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\raccount.proto\022\024com.mm.account.proto\"\204\001" +
      "\n\017AccountUserInfo\022\017\n\007version\030\001 \002(\005\022\013\n\003ui" +
      "d\030\002 \002(\005\022,\n\006gender\030\003 \001(\0162\034.com.mm.account" +
      ".proto.Gender\022\022\n\nfirst_name\030\004 \001(\t\022\021\n\tlas" +
      "t_name\030\005 \001(\t\"\212\001\n\020AccountPhoneInfo\022\013\n\003uid" +
      "\030\001 \002(\005\022\021\n\tphone_num\030\002 \002(\005\022\014\n\004imei\030\003 \001(\t\022" +
      "\021\n\tdevice_id\030\004 \001(\t\0225\n\013device_type\030\005 \001(\0162" +
      " .com.mm.account.proto.DeviceType*\036\n\006Gen" +
      "der\022\010\n\004MALE\020\001\022\n\n\006FEMALE\020\002*\"\n\nDeviceType\022" +
      "\013\n\007ANDROID\020\001\022\007\n\003IOS\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mm_account_proto_AccountUserInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mm_account_proto_AccountUserInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mm_account_proto_AccountUserInfo_descriptor,
              new java.lang.String[] { "Version", "Uid", "Gender", "FirstName", "LastName", });
          internal_static_com_mm_account_proto_AccountPhoneInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_mm_account_proto_AccountPhoneInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mm_account_proto_AccountPhoneInfo_descriptor,
              new java.lang.String[] { "Uid", "PhoneNum", "Imei", "DeviceId", "DeviceType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
