// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.mm.account.proto;

public final class Account {
  private Account() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.mm.account.proto.Gender}
   */
  public enum Gender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MALE = 1;</code>
     */
    MALE(0, 1),
    /**
     * <code>FEMALE = 0;</code>
     */
    FEMALE(1, 0),
    ;

    /**
     * <code>MALE = 1;</code>
     */
    public static final int MALE_VALUE = 1;
    /**
     * <code>FEMALE = 0;</code>
     */
    public static final int FEMALE_VALUE = 0;


    public final int getNumber() { return value; }

    public static Gender valueOf(int value) {
      switch (value) {
        case 1: return MALE;
        case 0: return FEMALE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.mm.account.proto.Account.getDescriptor().getEnumTypes().get(0);
    }

    private static final Gender[] VALUES = values();

    public static Gender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Gender(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.mm.account.proto.Gender)
  }

  /**
   * Protobuf enum {@code com.mm.account.proto.DeviceType}
   */
  public enum DeviceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ANDROID = 1;</code>
     */
    ANDROID(0, 1),
    /**
     * <code>IOS = 2;</code>
     */
    IOS(1, 2),
    ;

    /**
     * <code>ANDROID = 1;</code>
     */
    public static final int ANDROID_VALUE = 1;
    /**
     * <code>IOS = 2;</code>
     */
    public static final int IOS_VALUE = 2;


    public final int getNumber() { return value; }

    public static DeviceType valueOf(int value) {
      switch (value) {
        case 1: return ANDROID;
        case 2: return IOS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DeviceType>() {
            public DeviceType findValueByNumber(int number) {
              return DeviceType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.mm.account.proto.Account.getDescriptor().getEnumTypes().get(1);
    }

    private static final DeviceType[] VALUES = values();

    public static DeviceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private DeviceType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.mm.account.proto.DeviceType)
  }

  public interface UserDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 version = 1 [default = 0];
    /**
     * <code>required int32 version = 1 [default = 0];</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1 [default = 0];</code>
     */
    int getVersion();

    // required int64 uid = 2;
    /**
     * <code>required int64 uid = 2;</code>
     */
    boolean hasUid();
    /**
     * <code>required int64 uid = 2;</code>
     */
    long getUid();

    // optional .com.mm.account.proto.Gender gender = 3;
    /**
     * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
     */
    boolean hasGender();
    /**
     * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
     */
    com.mm.account.proto.Account.Gender getGender();

    // optional string first_name = 4;
    /**
     * <code>optional string first_name = 4;</code>
     */
    boolean hasFirstName();
    /**
     * <code>optional string first_name = 4;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>optional string first_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    // optional string last_name = 5;
    /**
     * <code>optional string last_name = 5;</code>
     */
    boolean hasLastName();
    /**
     * <code>optional string last_name = 5;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>optional string last_name = 5;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    // optional string head_url = 6;
    /**
     * <code>optional string head_url = 6;</code>
     */
    boolean hasHeadUrl();
    /**
     * <code>optional string head_url = 6;</code>
     */
    java.lang.String getHeadUrl();
    /**
     * <code>optional string head_url = 6;</code>
     */
    com.google.protobuf.ByteString
        getHeadUrlBytes();
  }
  /**
   * Protobuf type {@code com.mm.account.proto.UserData}
   */
  public static final class UserData extends
      com.google.protobuf.GeneratedMessage
      implements UserDataOrBuilder {
    // Use UserData.newBuilder() to construct.
    private UserData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserData defaultInstance;
    public static UserData getDefaultInstance() {
      return defaultInstance;
    }

    public UserData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              uid_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.mm.account.proto.Account.Gender value = com.mm.account.proto.Account.Gender.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                gender_ = value;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              firstName_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              lastName_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              headUrl_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mm.account.proto.Account.internal_static_com_mm_account_proto_UserData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mm.account.proto.Account.internal_static_com_mm_account_proto_UserData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mm.account.proto.Account.UserData.class, com.mm.account.proto.Account.UserData.Builder.class);
    }

    public static com.google.protobuf.Parser<UserData> PARSER =
        new com.google.protobuf.AbstractParser<UserData>() {
      public UserData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 version = 1 [default = 0];
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1 [default = 0];</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1 [default = 0];</code>
     */
    public int getVersion() {
      return version_;
    }

    // required int64 uid = 2;
    public static final int UID_FIELD_NUMBER = 2;
    private long uid_;
    /**
     * <code>required int64 uid = 2;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 uid = 2;</code>
     */
    public long getUid() {
      return uid_;
    }

    // optional .com.mm.account.proto.Gender gender = 3;
    public static final int GENDER_FIELD_NUMBER = 3;
    private com.mm.account.proto.Account.Gender gender_;
    /**
     * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
     */
    public boolean hasGender() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
     */
    public com.mm.account.proto.Account.Gender getGender() {
      return gender_;
    }

    // optional string first_name = 4;
    public static final int FIRST_NAME_FIELD_NUMBER = 4;
    private java.lang.Object firstName_;
    /**
     * <code>optional string first_name = 4;</code>
     */
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string first_name = 4;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string first_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string last_name = 5;
    public static final int LAST_NAME_FIELD_NUMBER = 5;
    private java.lang.Object lastName_;
    /**
     * <code>optional string last_name = 5;</code>
     */
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string last_name = 5;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string last_name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string head_url = 6;
    public static final int HEAD_URL_FIELD_NUMBER = 6;
    private java.lang.Object headUrl_;
    /**
     * <code>optional string head_url = 6;</code>
     */
    public boolean hasHeadUrl() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string head_url = 6;</code>
     */
    public java.lang.String getHeadUrl() {
      java.lang.Object ref = headUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          headUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string head_url = 6;</code>
     */
    public com.google.protobuf.ByteString
        getHeadUrlBytes() {
      java.lang.Object ref = headUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      version_ = 0;
      uid_ = 0L;
      gender_ = com.mm.account.proto.Account.Gender.MALE;
      firstName_ = "";
      lastName_ = "";
      headUrl_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, uid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, gender_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getLastNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getHeadUrlBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, uid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, gender_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getLastNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getHeadUrlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mm.account.proto.Account.UserData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mm.account.proto.Account.UserData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mm.account.proto.Account.UserData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mm.account.proto.Account.UserData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mm.account.proto.Account.UserData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mm.account.proto.Account.UserData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mm.account.proto.Account.UserData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mm.account.proto.Account.UserData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mm.account.proto.Account.UserData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mm.account.proto.Account.UserData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mm.account.proto.Account.UserData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mm.account.proto.UserData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mm.account.proto.Account.UserDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mm.account.proto.Account.internal_static_com_mm_account_proto_UserData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mm.account.proto.Account.internal_static_com_mm_account_proto_UserData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mm.account.proto.Account.UserData.class, com.mm.account.proto.Account.UserData.Builder.class);
      }

      // Construct using com.mm.account.proto.Account.UserData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        gender_ = com.mm.account.proto.Account.Gender.MALE;
        bitField0_ = (bitField0_ & ~0x00000004);
        firstName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        lastName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        headUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mm.account.proto.Account.internal_static_com_mm_account_proto_UserData_descriptor;
      }

      public com.mm.account.proto.Account.UserData getDefaultInstanceForType() {
        return com.mm.account.proto.Account.UserData.getDefaultInstance();
      }

      public com.mm.account.proto.Account.UserData build() {
        com.mm.account.proto.Account.UserData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mm.account.proto.Account.UserData buildPartial() {
        com.mm.account.proto.Account.UserData result = new com.mm.account.proto.Account.UserData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gender_ = gender_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.firstName_ = firstName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.lastName_ = lastName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.headUrl_ = headUrl_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mm.account.proto.Account.UserData) {
          return mergeFrom((com.mm.account.proto.Account.UserData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mm.account.proto.Account.UserData other) {
        if (other == com.mm.account.proto.Account.UserData.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasGender()) {
          setGender(other.getGender());
        }
        if (other.hasFirstName()) {
          bitField0_ |= 0x00000008;
          firstName_ = other.firstName_;
          onChanged();
        }
        if (other.hasLastName()) {
          bitField0_ |= 0x00000010;
          lastName_ = other.lastName_;
          onChanged();
        }
        if (other.hasHeadUrl()) {
          bitField0_ |= 0x00000020;
          headUrl_ = other.headUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasUid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mm.account.proto.Account.UserData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mm.account.proto.Account.UserData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 version = 1 [default = 0];
      private int version_ ;
      /**
       * <code>required int32 version = 1 [default = 0];</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 version = 1 [default = 0];</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 1 [default = 0];</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 1 [default = 0];</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      // required int64 uid = 2;
      private long uid_ ;
      /**
       * <code>required int64 uid = 2;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 uid = 2;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>required int64 uid = 2;</code>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000002;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 uid = 2;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uid_ = 0L;
        onChanged();
        return this;
      }

      // optional .com.mm.account.proto.Gender gender = 3;
      private com.mm.account.proto.Account.Gender gender_ = com.mm.account.proto.Account.Gender.MALE;
      /**
       * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
       */
      public boolean hasGender() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
       */
      public com.mm.account.proto.Account.Gender getGender() {
        return gender_;
      }
      /**
       * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
       */
      public Builder setGender(com.mm.account.proto.Account.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.mm.account.proto.Gender gender = 3;</code>
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gender_ = com.mm.account.proto.Account.Gender.MALE;
        onChanged();
        return this;
      }

      // optional string first_name = 4;
      private java.lang.Object firstName_ = "";
      /**
       * <code>optional string first_name = 4;</code>
       */
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string first_name = 4;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string first_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string first_name = 4;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string first_name = 4;</code>
       */
      public Builder clearFirstName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string first_name = 4;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        firstName_ = value;
        onChanged();
        return this;
      }

      // optional string last_name = 5;
      private java.lang.Object lastName_ = "";
      /**
       * <code>optional string last_name = 5;</code>
       */
      public boolean hasLastName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string last_name = 5;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string last_name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string last_name = 5;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string last_name = 5;</code>
       */
      public Builder clearLastName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string last_name = 5;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        lastName_ = value;
        onChanged();
        return this;
      }

      // optional string head_url = 6;
      private java.lang.Object headUrl_ = "";
      /**
       * <code>optional string head_url = 6;</code>
       */
      public boolean hasHeadUrl() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string head_url = 6;</code>
       */
      public java.lang.String getHeadUrl() {
        java.lang.Object ref = headUrl_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          headUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string head_url = 6;</code>
       */
      public com.google.protobuf.ByteString
          getHeadUrlBytes() {
        java.lang.Object ref = headUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string head_url = 6;</code>
       */
      public Builder setHeadUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        headUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string head_url = 6;</code>
       */
      public Builder clearHeadUrl() {
        bitField0_ = (bitField0_ & ~0x00000020);
        headUrl_ = getDefaultInstance().getHeadUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string head_url = 6;</code>
       */
      public Builder setHeadUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        headUrl_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mm.account.proto.UserData)
    }

    static {
      defaultInstance = new UserData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mm.account.proto.UserData)
  }

  public interface UserRelateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 userid_a = 1;
    /**
     * <code>required int64 userid_a = 1;</code>
     */
    boolean hasUseridA();
    /**
     * <code>required int64 userid_a = 1;</code>
     */
    long getUseridA();

    // required int64 userid_b = 2;
    /**
     * <code>required int64 userid_b = 2;</code>
     */
    boolean hasUseridB();
    /**
     * <code>required int64 userid_b = 2;</code>
     */
    long getUseridB();

    // optional string a_ask_b = 3;
    /**
     * <code>optional string a_ask_b = 3;</code>
     */
    boolean hasAAskB();
    /**
     * <code>optional string a_ask_b = 3;</code>
     */
    java.lang.String getAAskB();
    /**
     * <code>optional string a_ask_b = 3;</code>
     */
    com.google.protobuf.ByteString
        getAAskBBytes();

    // optional string b_ask_a = 4;
    /**
     * <code>optional string b_ask_a = 4;</code>
     */
    boolean hasBAskA();
    /**
     * <code>optional string b_ask_a = 4;</code>
     */
    java.lang.String getBAskA();
    /**
     * <code>optional string b_ask_a = 4;</code>
     */
    com.google.protobuf.ByteString
        getBAskABytes();

    // required bool a_b_pair = 5 [default = false];
    /**
     * <code>required bool a_b_pair = 5 [default = false];</code>
     */
    boolean hasABPair();
    /**
     * <code>required bool a_b_pair = 5 [default = false];</code>
     */
    boolean getABPair();
  }
  /**
   * Protobuf type {@code com.mm.account.proto.UserRelate}
   */
  public static final class UserRelate extends
      com.google.protobuf.GeneratedMessage
      implements UserRelateOrBuilder {
    // Use UserRelate.newBuilder() to construct.
    private UserRelate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserRelate(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserRelate defaultInstance;
    public static UserRelate getDefaultInstance() {
      return defaultInstance;
    }

    public UserRelate getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserRelate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              useridA_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              useridB_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              aAskB_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              bAskA_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              aBPair_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mm.account.proto.Account.internal_static_com_mm_account_proto_UserRelate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mm.account.proto.Account.internal_static_com_mm_account_proto_UserRelate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mm.account.proto.Account.UserRelate.class, com.mm.account.proto.Account.UserRelate.Builder.class);
    }

    public static com.google.protobuf.Parser<UserRelate> PARSER =
        new com.google.protobuf.AbstractParser<UserRelate>() {
      public UserRelate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserRelate(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserRelate> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 userid_a = 1;
    public static final int USERID_A_FIELD_NUMBER = 1;
    private long useridA_;
    /**
     * <code>required int64 userid_a = 1;</code>
     */
    public boolean hasUseridA() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 userid_a = 1;</code>
     */
    public long getUseridA() {
      return useridA_;
    }

    // required int64 userid_b = 2;
    public static final int USERID_B_FIELD_NUMBER = 2;
    private long useridB_;
    /**
     * <code>required int64 userid_b = 2;</code>
     */
    public boolean hasUseridB() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 userid_b = 2;</code>
     */
    public long getUseridB() {
      return useridB_;
    }

    // optional string a_ask_b = 3;
    public static final int A_ASK_B_FIELD_NUMBER = 3;
    private java.lang.Object aAskB_;
    /**
     * <code>optional string a_ask_b = 3;</code>
     */
    public boolean hasAAskB() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string a_ask_b = 3;</code>
     */
    public java.lang.String getAAskB() {
      java.lang.Object ref = aAskB_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          aAskB_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string a_ask_b = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAAskBBytes() {
      java.lang.Object ref = aAskB_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aAskB_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string b_ask_a = 4;
    public static final int B_ASK_A_FIELD_NUMBER = 4;
    private java.lang.Object bAskA_;
    /**
     * <code>optional string b_ask_a = 4;</code>
     */
    public boolean hasBAskA() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string b_ask_a = 4;</code>
     */
    public java.lang.String getBAskA() {
      java.lang.Object ref = bAskA_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bAskA_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string b_ask_a = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBAskABytes() {
      java.lang.Object ref = bAskA_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bAskA_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bool a_b_pair = 5 [default = false];
    public static final int A_B_PAIR_FIELD_NUMBER = 5;
    private boolean aBPair_;
    /**
     * <code>required bool a_b_pair = 5 [default = false];</code>
     */
    public boolean hasABPair() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool a_b_pair = 5 [default = false];</code>
     */
    public boolean getABPair() {
      return aBPair_;
    }

    private void initFields() {
      useridA_ = 0L;
      useridB_ = 0L;
      aAskB_ = "";
      bAskA_ = "";
      aBPair_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUseridA()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUseridB()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasABPair()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, useridA_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, useridB_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAAskBBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getBAskABytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, aBPair_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, useridA_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, useridB_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAAskBBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getBAskABytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, aBPair_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mm.account.proto.Account.UserRelate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mm.account.proto.Account.UserRelate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mm.account.proto.Account.UserRelate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mm.account.proto.Account.UserRelate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mm.account.proto.Account.UserRelate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mm.account.proto.Account.UserRelate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mm.account.proto.Account.UserRelate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mm.account.proto.Account.UserRelate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mm.account.proto.Account.UserRelate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mm.account.proto.Account.UserRelate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mm.account.proto.Account.UserRelate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mm.account.proto.UserRelate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mm.account.proto.Account.UserRelateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mm.account.proto.Account.internal_static_com_mm_account_proto_UserRelate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mm.account.proto.Account.internal_static_com_mm_account_proto_UserRelate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mm.account.proto.Account.UserRelate.class, com.mm.account.proto.Account.UserRelate.Builder.class);
      }

      // Construct using com.mm.account.proto.Account.UserRelate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        useridA_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        useridB_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        aAskB_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        bAskA_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        aBPair_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mm.account.proto.Account.internal_static_com_mm_account_proto_UserRelate_descriptor;
      }

      public com.mm.account.proto.Account.UserRelate getDefaultInstanceForType() {
        return com.mm.account.proto.Account.UserRelate.getDefaultInstance();
      }

      public com.mm.account.proto.Account.UserRelate build() {
        com.mm.account.proto.Account.UserRelate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mm.account.proto.Account.UserRelate buildPartial() {
        com.mm.account.proto.Account.UserRelate result = new com.mm.account.proto.Account.UserRelate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.useridA_ = useridA_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.useridB_ = useridB_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.aAskB_ = aAskB_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.bAskA_ = bAskA_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.aBPair_ = aBPair_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mm.account.proto.Account.UserRelate) {
          return mergeFrom((com.mm.account.proto.Account.UserRelate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mm.account.proto.Account.UserRelate other) {
        if (other == com.mm.account.proto.Account.UserRelate.getDefaultInstance()) return this;
        if (other.hasUseridA()) {
          setUseridA(other.getUseridA());
        }
        if (other.hasUseridB()) {
          setUseridB(other.getUseridB());
        }
        if (other.hasAAskB()) {
          bitField0_ |= 0x00000004;
          aAskB_ = other.aAskB_;
          onChanged();
        }
        if (other.hasBAskA()) {
          bitField0_ |= 0x00000008;
          bAskA_ = other.bAskA_;
          onChanged();
        }
        if (other.hasABPair()) {
          setABPair(other.getABPair());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUseridA()) {
          
          return false;
        }
        if (!hasUseridB()) {
          
          return false;
        }
        if (!hasABPair()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mm.account.proto.Account.UserRelate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mm.account.proto.Account.UserRelate) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 userid_a = 1;
      private long useridA_ ;
      /**
       * <code>required int64 userid_a = 1;</code>
       */
      public boolean hasUseridA() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 userid_a = 1;</code>
       */
      public long getUseridA() {
        return useridA_;
      }
      /**
       * <code>required int64 userid_a = 1;</code>
       */
      public Builder setUseridA(long value) {
        bitField0_ |= 0x00000001;
        useridA_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 userid_a = 1;</code>
       */
      public Builder clearUseridA() {
        bitField0_ = (bitField0_ & ~0x00000001);
        useridA_ = 0L;
        onChanged();
        return this;
      }

      // required int64 userid_b = 2;
      private long useridB_ ;
      /**
       * <code>required int64 userid_b = 2;</code>
       */
      public boolean hasUseridB() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 userid_b = 2;</code>
       */
      public long getUseridB() {
        return useridB_;
      }
      /**
       * <code>required int64 userid_b = 2;</code>
       */
      public Builder setUseridB(long value) {
        bitField0_ |= 0x00000002;
        useridB_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 userid_b = 2;</code>
       */
      public Builder clearUseridB() {
        bitField0_ = (bitField0_ & ~0x00000002);
        useridB_ = 0L;
        onChanged();
        return this;
      }

      // optional string a_ask_b = 3;
      private java.lang.Object aAskB_ = "";
      /**
       * <code>optional string a_ask_b = 3;</code>
       */
      public boolean hasAAskB() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string a_ask_b = 3;</code>
       */
      public java.lang.String getAAskB() {
        java.lang.Object ref = aAskB_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          aAskB_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string a_ask_b = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAAskBBytes() {
        java.lang.Object ref = aAskB_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          aAskB_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string a_ask_b = 3;</code>
       */
      public Builder setAAskB(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        aAskB_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string a_ask_b = 3;</code>
       */
      public Builder clearAAskB() {
        bitField0_ = (bitField0_ & ~0x00000004);
        aAskB_ = getDefaultInstance().getAAskB();
        onChanged();
        return this;
      }
      /**
       * <code>optional string a_ask_b = 3;</code>
       */
      public Builder setAAskBBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        aAskB_ = value;
        onChanged();
        return this;
      }

      // optional string b_ask_a = 4;
      private java.lang.Object bAskA_ = "";
      /**
       * <code>optional string b_ask_a = 4;</code>
       */
      public boolean hasBAskA() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string b_ask_a = 4;</code>
       */
      public java.lang.String getBAskA() {
        java.lang.Object ref = bAskA_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          bAskA_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string b_ask_a = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBAskABytes() {
        java.lang.Object ref = bAskA_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bAskA_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string b_ask_a = 4;</code>
       */
      public Builder setBAskA(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        bAskA_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string b_ask_a = 4;</code>
       */
      public Builder clearBAskA() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bAskA_ = getDefaultInstance().getBAskA();
        onChanged();
        return this;
      }
      /**
       * <code>optional string b_ask_a = 4;</code>
       */
      public Builder setBAskABytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        bAskA_ = value;
        onChanged();
        return this;
      }

      // required bool a_b_pair = 5 [default = false];
      private boolean aBPair_ ;
      /**
       * <code>required bool a_b_pair = 5 [default = false];</code>
       */
      public boolean hasABPair() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bool a_b_pair = 5 [default = false];</code>
       */
      public boolean getABPair() {
        return aBPair_;
      }
      /**
       * <code>required bool a_b_pair = 5 [default = false];</code>
       */
      public Builder setABPair(boolean value) {
        bitField0_ |= 0x00000010;
        aBPair_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool a_b_pair = 5 [default = false];</code>
       */
      public Builder clearABPair() {
        bitField0_ = (bitField0_ & ~0x00000010);
        aBPair_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mm.account.proto.UserRelate)
    }

    static {
      defaultInstance = new UserRelate(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mm.account.proto.UserRelate)
  }

  public interface UserPhoneInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 uid = 1;
    /**
     * <code>required int32 uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required int32 uid = 1;</code>
     */
    int getUid();

    // required int32 phone_num = 2;
    /**
     * <code>required int32 phone_num = 2;</code>
     */
    boolean hasPhoneNum();
    /**
     * <code>required int32 phone_num = 2;</code>
     */
    int getPhoneNum();

    // optional string imei = 3;
    /**
     * <code>optional string imei = 3;</code>
     */
    boolean hasImei();
    /**
     * <code>optional string imei = 3;</code>
     */
    java.lang.String getImei();
    /**
     * <code>optional string imei = 3;</code>
     */
    com.google.protobuf.ByteString
        getImeiBytes();

    // optional string device_id = 4;
    /**
     * <code>optional string device_id = 4;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>optional string device_id = 4;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>optional string device_id = 4;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    // optional .com.mm.account.proto.DeviceType device_type = 5;
    /**
     * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
     */
    boolean hasDeviceType();
    /**
     * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
     */
    com.mm.account.proto.Account.DeviceType getDeviceType();
  }
  /**
   * Protobuf type {@code com.mm.account.proto.UserPhoneInfo}
   */
  public static final class UserPhoneInfo extends
      com.google.protobuf.GeneratedMessage
      implements UserPhoneInfoOrBuilder {
    // Use UserPhoneInfo.newBuilder() to construct.
    private UserPhoneInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserPhoneInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserPhoneInfo defaultInstance;
    public static UserPhoneInfo getDefaultInstance() {
      return defaultInstance;
    }

    public UserPhoneInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserPhoneInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              phoneNum_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              imei_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              deviceId_ = input.readBytes();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.mm.account.proto.Account.DeviceType value = com.mm.account.proto.Account.DeviceType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                deviceType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mm.account.proto.Account.internal_static_com_mm_account_proto_UserPhoneInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mm.account.proto.Account.internal_static_com_mm_account_proto_UserPhoneInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mm.account.proto.Account.UserPhoneInfo.class, com.mm.account.proto.Account.UserPhoneInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<UserPhoneInfo> PARSER =
        new com.google.protobuf.AbstractParser<UserPhoneInfo>() {
      public UserPhoneInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserPhoneInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserPhoneInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 uid = 1;
    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>required int32 uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }

    // required int32 phone_num = 2;
    public static final int PHONE_NUM_FIELD_NUMBER = 2;
    private int phoneNum_;
    /**
     * <code>required int32 phone_num = 2;</code>
     */
    public boolean hasPhoneNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 phone_num = 2;</code>
     */
    public int getPhoneNum() {
      return phoneNum_;
    }

    // optional string imei = 3;
    public static final int IMEI_FIELD_NUMBER = 3;
    private java.lang.Object imei_;
    /**
     * <code>optional string imei = 3;</code>
     */
    public boolean hasImei() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string imei = 3;</code>
     */
    public java.lang.String getImei() {
      java.lang.Object ref = imei_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imei_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string imei = 3;</code>
     */
    public com.google.protobuf.ByteString
        getImeiBytes() {
      java.lang.Object ref = imei_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string device_id = 4;
    public static final int DEVICE_ID_FIELD_NUMBER = 4;
    private java.lang.Object deviceId_;
    /**
     * <code>optional string device_id = 4;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string device_id = 4;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string device_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .com.mm.account.proto.DeviceType device_type = 5;
    public static final int DEVICE_TYPE_FIELD_NUMBER = 5;
    private com.mm.account.proto.Account.DeviceType deviceType_;
    /**
     * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
     */
    public boolean hasDeviceType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
     */
    public com.mm.account.proto.Account.DeviceType getDeviceType() {
      return deviceType_;
    }

    private void initFields() {
      uid_ = 0;
      phoneNum_ = 0;
      imei_ = "";
      deviceId_ = "";
      deviceType_ = com.mm.account.proto.Account.DeviceType.ANDROID;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPhoneNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, phoneNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getImeiBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, deviceType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, phoneNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getImeiBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, deviceType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mm.account.proto.Account.UserPhoneInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mm.account.proto.Account.UserPhoneInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mm.account.proto.Account.UserPhoneInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mm.account.proto.Account.UserPhoneInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mm.account.proto.Account.UserPhoneInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mm.account.proto.Account.UserPhoneInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mm.account.proto.Account.UserPhoneInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mm.account.proto.Account.UserPhoneInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mm.account.proto.Account.UserPhoneInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mm.account.proto.Account.UserPhoneInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mm.account.proto.Account.UserPhoneInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mm.account.proto.UserPhoneInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mm.account.proto.Account.UserPhoneInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mm.account.proto.Account.internal_static_com_mm_account_proto_UserPhoneInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mm.account.proto.Account.internal_static_com_mm_account_proto_UserPhoneInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mm.account.proto.Account.UserPhoneInfo.class, com.mm.account.proto.Account.UserPhoneInfo.Builder.class);
      }

      // Construct using com.mm.account.proto.Account.UserPhoneInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        phoneNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        imei_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceType_ = com.mm.account.proto.Account.DeviceType.ANDROID;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mm.account.proto.Account.internal_static_com_mm_account_proto_UserPhoneInfo_descriptor;
      }

      public com.mm.account.proto.Account.UserPhoneInfo getDefaultInstanceForType() {
        return com.mm.account.proto.Account.UserPhoneInfo.getDefaultInstance();
      }

      public com.mm.account.proto.Account.UserPhoneInfo build() {
        com.mm.account.proto.Account.UserPhoneInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mm.account.proto.Account.UserPhoneInfo buildPartial() {
        com.mm.account.proto.Account.UserPhoneInfo result = new com.mm.account.proto.Account.UserPhoneInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.phoneNum_ = phoneNum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.imei_ = imei_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.deviceType_ = deviceType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mm.account.proto.Account.UserPhoneInfo) {
          return mergeFrom((com.mm.account.proto.Account.UserPhoneInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mm.account.proto.Account.UserPhoneInfo other) {
        if (other == com.mm.account.proto.Account.UserPhoneInfo.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasPhoneNum()) {
          setPhoneNum(other.getPhoneNum());
        }
        if (other.hasImei()) {
          bitField0_ |= 0x00000004;
          imei_ = other.imei_;
          onChanged();
        }
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000008;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasDeviceType()) {
          setDeviceType(other.getDeviceType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        if (!hasPhoneNum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mm.account.proto.Account.UserPhoneInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mm.account.proto.Account.UserPhoneInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 uid = 1;
      private int uid_ ;
      /**
       * <code>required int32 uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 uid = 1;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>required int32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0;
        onChanged();
        return this;
      }

      // required int32 phone_num = 2;
      private int phoneNum_ ;
      /**
       * <code>required int32 phone_num = 2;</code>
       */
      public boolean hasPhoneNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 phone_num = 2;</code>
       */
      public int getPhoneNum() {
        return phoneNum_;
      }
      /**
       * <code>required int32 phone_num = 2;</code>
       */
      public Builder setPhoneNum(int value) {
        bitField0_ |= 0x00000002;
        phoneNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 phone_num = 2;</code>
       */
      public Builder clearPhoneNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        phoneNum_ = 0;
        onChanged();
        return this;
      }

      // optional string imei = 3;
      private java.lang.Object imei_ = "";
      /**
       * <code>optional string imei = 3;</code>
       */
      public boolean hasImei() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string imei = 3;</code>
       */
      public java.lang.String getImei() {
        java.lang.Object ref = imei_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          imei_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string imei = 3;</code>
       */
      public com.google.protobuf.ByteString
          getImeiBytes() {
        java.lang.Object ref = imei_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imei_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string imei = 3;</code>
       */
      public Builder setImei(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        imei_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string imei = 3;</code>
       */
      public Builder clearImei() {
        bitField0_ = (bitField0_ & ~0x00000004);
        imei_ = getDefaultInstance().getImei();
        onChanged();
        return this;
      }
      /**
       * <code>optional string imei = 3;</code>
       */
      public Builder setImeiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        imei_ = value;
        onChanged();
        return this;
      }

      // optional string device_id = 4;
      private java.lang.Object deviceId_ = "";
      /**
       * <code>optional string device_id = 4;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string device_id = 4;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_id = 4;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_id = 4;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_id = 4;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceId_ = value;
        onChanged();
        return this;
      }

      // optional .com.mm.account.proto.DeviceType device_type = 5;
      private com.mm.account.proto.Account.DeviceType deviceType_ = com.mm.account.proto.Account.DeviceType.ANDROID;
      /**
       * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
       */
      public boolean hasDeviceType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
       */
      public com.mm.account.proto.Account.DeviceType getDeviceType() {
        return deviceType_;
      }
      /**
       * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
       */
      public Builder setDeviceType(com.mm.account.proto.Account.DeviceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.mm.account.proto.DeviceType device_type = 5;</code>
       */
      public Builder clearDeviceType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        deviceType_ = com.mm.account.proto.Account.DeviceType.ANDROID;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mm.account.proto.UserPhoneInfo)
    }

    static {
      defaultInstance = new UserPhoneInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mm.account.proto.UserPhoneInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mm_account_proto_UserData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mm_account_proto_UserData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mm_account_proto_UserRelate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mm_account_proto_UserRelate_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mm_account_proto_UserPhoneInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mm_account_proto_UserPhoneInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\raccount.proto\022\024com.mm.account.proto\"\222\001" +
      "\n\010UserData\022\022\n\007version\030\001 \002(\005:\0010\022\013\n\003uid\030\002 " +
      "\002(\003\022,\n\006gender\030\003 \001(\0162\034.com.mm.account.pro" +
      "to.Gender\022\022\n\nfirst_name\030\004 \001(\t\022\021\n\tlast_na" +
      "me\030\005 \001(\t\022\020\n\010head_url\030\006 \001(\t\"k\n\nUserRelate" +
      "\022\020\n\010userid_a\030\001 \002(\003\022\020\n\010userid_b\030\002 \002(\003\022\017\n\007" +
      "a_ask_b\030\003 \001(\t\022\017\n\007b_ask_a\030\004 \001(\t\022\027\n\010a_b_pa" +
      "ir\030\005 \002(\010:\005false\"\207\001\n\rUserPhoneInfo\022\013\n\003uid" +
      "\030\001 \002(\005\022\021\n\tphone_num\030\002 \002(\005\022\014\n\004imei\030\003 \001(\t\022" +
      "\021\n\tdevice_id\030\004 \001(\t\0225\n\013device_type\030\005 \001(\0162",
      " .com.mm.account.proto.DeviceType*\036\n\006Gen" +
      "der\022\010\n\004MALE\020\001\022\n\n\006FEMALE\020\000*\"\n\nDeviceType\022" +
      "\013\n\007ANDROID\020\001\022\007\n\003IOS\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mm_account_proto_UserData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mm_account_proto_UserData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mm_account_proto_UserData_descriptor,
              new java.lang.String[] { "Version", "Uid", "Gender", "FirstName", "LastName", "HeadUrl", });
          internal_static_com_mm_account_proto_UserRelate_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_mm_account_proto_UserRelate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mm_account_proto_UserRelate_descriptor,
              new java.lang.String[] { "UseridA", "UseridB", "AAskB", "BAskA", "ABPair", });
          internal_static_com_mm_account_proto_UserPhoneInfo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_mm_account_proto_UserPhoneInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mm_account_proto_UserPhoneInfo_descriptor,
              new java.lang.String[] { "Uid", "PhoneNum", "Imei", "DeviceId", "DeviceType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
