// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package com.mm.photo.proto;

public final class Storage {
  private Storage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ImageKeyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string url = 1;
    /**
     * <code>required string url = 1;</code>
     */
    boolean hasUrl();
    /**
     * <code>required string url = 1;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>required string url = 1;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();
  }
  /**
   * Protobuf type {@code com.mm.photo.proto.ImageKey}
   */
  public static final class ImageKey extends
      com.google.protobuf.GeneratedMessage
      implements ImageKeyOrBuilder {
    // Use ImageKey.newBuilder() to construct.
    private ImageKey(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ImageKey(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ImageKey defaultInstance;
    public static ImageKey getDefaultInstance() {
      return defaultInstance;
    }

    public ImageKey getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ImageKey(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              url_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mm.photo.proto.Storage.internal_static_com_mm_photo_proto_ImageKey_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mm.photo.proto.Storage.internal_static_com_mm_photo_proto_ImageKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mm.photo.proto.Storage.ImageKey.class, com.mm.photo.proto.Storage.ImageKey.Builder.class);
    }

    public static com.google.protobuf.Parser<ImageKey> PARSER =
        new com.google.protobuf.AbstractParser<ImageKey>() {
      public ImageKey parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImageKey(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ImageKey> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string url = 1;
    public static final int URL_FIELD_NUMBER = 1;
    private java.lang.Object url_;
    /**
     * <code>required string url = 1;</code>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string url = 1;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      url_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUrlBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUrlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mm.photo.proto.Storage.ImageKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mm.photo.proto.Storage.ImageKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mm.photo.proto.Storage.ImageKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mm.photo.proto.Storage.ImageKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mm.photo.proto.Storage.ImageKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mm.photo.proto.Storage.ImageKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mm.photo.proto.Storage.ImageKey parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mm.photo.proto.Storage.ImageKey parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mm.photo.proto.Storage.ImageKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mm.photo.proto.Storage.ImageKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mm.photo.proto.Storage.ImageKey prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mm.photo.proto.ImageKey}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mm.photo.proto.Storage.ImageKeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mm.photo.proto.Storage.internal_static_com_mm_photo_proto_ImageKey_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mm.photo.proto.Storage.internal_static_com_mm_photo_proto_ImageKey_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mm.photo.proto.Storage.ImageKey.class, com.mm.photo.proto.Storage.ImageKey.Builder.class);
      }

      // Construct using com.mm.photo.proto.Storage.ImageKey.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mm.photo.proto.Storage.internal_static_com_mm_photo_proto_ImageKey_descriptor;
      }

      public com.mm.photo.proto.Storage.ImageKey getDefaultInstanceForType() {
        return com.mm.photo.proto.Storage.ImageKey.getDefaultInstance();
      }

      public com.mm.photo.proto.Storage.ImageKey build() {
        com.mm.photo.proto.Storage.ImageKey result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mm.photo.proto.Storage.ImageKey buildPartial() {
        com.mm.photo.proto.Storage.ImageKey result = new com.mm.photo.proto.Storage.ImageKey(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.url_ = url_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mm.photo.proto.Storage.ImageKey) {
          return mergeFrom((com.mm.photo.proto.Storage.ImageKey)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mm.photo.proto.Storage.ImageKey other) {
        if (other == com.mm.photo.proto.Storage.ImageKey.getDefaultInstance()) return this;
        if (other.hasUrl()) {
          bitField0_ |= 0x00000001;
          url_ = other.url_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUrl()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mm.photo.proto.Storage.ImageKey parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mm.photo.proto.Storage.ImageKey) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string url = 1;
      private java.lang.Object url_ = "";
      /**
       * <code>required string url = 1;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string url = 1;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string url = 1;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 1;</code>
       */
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 1;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mm.photo.proto.ImageKey)
    }

    static {
      defaultInstance = new ImageKey(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mm.photo.proto.ImageKey)
  }

  public interface ImageFragInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool isSplit = 1 [default = false];
    /**
     * <code>required bool isSplit = 1 [default = false];</code>
     */
    boolean hasIsSplit();
    /**
     * <code>required bool isSplit = 1 [default = false];</code>
     */
    boolean getIsSplit();

    // repeated .com.mm.photo.proto.ImageKey frageKeys = 2;
    /**
     * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
     */
    java.util.List<com.mm.photo.proto.Storage.ImageKey> 
        getFrageKeysList();
    /**
     * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
     */
    com.mm.photo.proto.Storage.ImageKey getFrageKeys(int index);
    /**
     * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
     */
    int getFrageKeysCount();
    /**
     * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
     */
    java.util.List<? extends com.mm.photo.proto.Storage.ImageKeyOrBuilder> 
        getFrageKeysOrBuilderList();
    /**
     * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
     */
    com.mm.photo.proto.Storage.ImageKeyOrBuilder getFrageKeysOrBuilder(
        int index);

    // optional bytes data = 3;
    /**
     * <code>optional bytes data = 3;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();

    // required int64 length = 4;
    /**
     * <code>required int64 length = 4;</code>
     */
    boolean hasLength();
    /**
     * <code>required int64 length = 4;</code>
     */
    long getLength();
  }
  /**
   * Protobuf type {@code com.mm.photo.proto.ImageFragInfo}
   */
  public static final class ImageFragInfo extends
      com.google.protobuf.GeneratedMessage
      implements ImageFragInfoOrBuilder {
    // Use ImageFragInfo.newBuilder() to construct.
    private ImageFragInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ImageFragInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ImageFragInfo defaultInstance;
    public static ImageFragInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ImageFragInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ImageFragInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isSplit_ = input.readBool();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                frageKeys_ = new java.util.ArrayList<com.mm.photo.proto.Storage.ImageKey>();
                mutable_bitField0_ |= 0x00000002;
              }
              frageKeys_.add(input.readMessage(com.mm.photo.proto.Storage.ImageKey.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              length_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          frageKeys_ = java.util.Collections.unmodifiableList(frageKeys_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mm.photo.proto.Storage.internal_static_com_mm_photo_proto_ImageFragInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mm.photo.proto.Storage.internal_static_com_mm_photo_proto_ImageFragInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mm.photo.proto.Storage.ImageFragInfo.class, com.mm.photo.proto.Storage.ImageFragInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ImageFragInfo> PARSER =
        new com.google.protobuf.AbstractParser<ImageFragInfo>() {
      public ImageFragInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImageFragInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ImageFragInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool isSplit = 1 [default = false];
    public static final int ISSPLIT_FIELD_NUMBER = 1;
    private boolean isSplit_;
    /**
     * <code>required bool isSplit = 1 [default = false];</code>
     */
    public boolean hasIsSplit() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool isSplit = 1 [default = false];</code>
     */
    public boolean getIsSplit() {
      return isSplit_;
    }

    // repeated .com.mm.photo.proto.ImageKey frageKeys = 2;
    public static final int FRAGEKEYS_FIELD_NUMBER = 2;
    private java.util.List<com.mm.photo.proto.Storage.ImageKey> frageKeys_;
    /**
     * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
     */
    public java.util.List<com.mm.photo.proto.Storage.ImageKey> getFrageKeysList() {
      return frageKeys_;
    }
    /**
     * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
     */
    public java.util.List<? extends com.mm.photo.proto.Storage.ImageKeyOrBuilder> 
        getFrageKeysOrBuilderList() {
      return frageKeys_;
    }
    /**
     * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
     */
    public int getFrageKeysCount() {
      return frageKeys_.size();
    }
    /**
     * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
     */
    public com.mm.photo.proto.Storage.ImageKey getFrageKeys(int index) {
      return frageKeys_.get(index);
    }
    /**
     * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
     */
    public com.mm.photo.proto.Storage.ImageKeyOrBuilder getFrageKeysOrBuilder(
        int index) {
      return frageKeys_.get(index);
    }

    // optional bytes data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    // required int64 length = 4;
    public static final int LENGTH_FIELD_NUMBER = 4;
    private long length_;
    /**
     * <code>required int64 length = 4;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 length = 4;</code>
     */
    public long getLength() {
      return length_;
    }

    private void initFields() {
      isSplit_ = false;
      frageKeys_ = java.util.Collections.emptyList();
      data_ = com.google.protobuf.ByteString.EMPTY;
      length_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIsSplit()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getFrageKeysCount(); i++) {
        if (!getFrageKeys(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isSplit_);
      }
      for (int i = 0; i < frageKeys_.size(); i++) {
        output.writeMessage(2, frageKeys_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, length_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSplit_);
      }
      for (int i = 0; i < frageKeys_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, frageKeys_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, length_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mm.photo.proto.Storage.ImageFragInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mm.photo.proto.Storage.ImageFragInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mm.photo.proto.Storage.ImageFragInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mm.photo.proto.Storage.ImageFragInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mm.photo.proto.Storage.ImageFragInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mm.photo.proto.Storage.ImageFragInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mm.photo.proto.Storage.ImageFragInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mm.photo.proto.Storage.ImageFragInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mm.photo.proto.Storage.ImageFragInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mm.photo.proto.Storage.ImageFragInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mm.photo.proto.Storage.ImageFragInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mm.photo.proto.ImageFragInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mm.photo.proto.Storage.ImageFragInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mm.photo.proto.Storage.internal_static_com_mm_photo_proto_ImageFragInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mm.photo.proto.Storage.internal_static_com_mm_photo_proto_ImageFragInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mm.photo.proto.Storage.ImageFragInfo.class, com.mm.photo.proto.Storage.ImageFragInfo.Builder.class);
      }

      // Construct using com.mm.photo.proto.Storage.ImageFragInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFrageKeysFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isSplit_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (frageKeysBuilder_ == null) {
          frageKeys_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          frageKeysBuilder_.clear();
        }
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        length_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mm.photo.proto.Storage.internal_static_com_mm_photo_proto_ImageFragInfo_descriptor;
      }

      public com.mm.photo.proto.Storage.ImageFragInfo getDefaultInstanceForType() {
        return com.mm.photo.proto.Storage.ImageFragInfo.getDefaultInstance();
      }

      public com.mm.photo.proto.Storage.ImageFragInfo build() {
        com.mm.photo.proto.Storage.ImageFragInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mm.photo.proto.Storage.ImageFragInfo buildPartial() {
        com.mm.photo.proto.Storage.ImageFragInfo result = new com.mm.photo.proto.Storage.ImageFragInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isSplit_ = isSplit_;
        if (frageKeysBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            frageKeys_ = java.util.Collections.unmodifiableList(frageKeys_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.frageKeys_ = frageKeys_;
        } else {
          result.frageKeys_ = frageKeysBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.length_ = length_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mm.photo.proto.Storage.ImageFragInfo) {
          return mergeFrom((com.mm.photo.proto.Storage.ImageFragInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mm.photo.proto.Storage.ImageFragInfo other) {
        if (other == com.mm.photo.proto.Storage.ImageFragInfo.getDefaultInstance()) return this;
        if (other.hasIsSplit()) {
          setIsSplit(other.getIsSplit());
        }
        if (frageKeysBuilder_ == null) {
          if (!other.frageKeys_.isEmpty()) {
            if (frageKeys_.isEmpty()) {
              frageKeys_ = other.frageKeys_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureFrageKeysIsMutable();
              frageKeys_.addAll(other.frageKeys_);
            }
            onChanged();
          }
        } else {
          if (!other.frageKeys_.isEmpty()) {
            if (frageKeysBuilder_.isEmpty()) {
              frageKeysBuilder_.dispose();
              frageKeysBuilder_ = null;
              frageKeys_ = other.frageKeys_;
              bitField0_ = (bitField0_ & ~0x00000002);
              frageKeysBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFrageKeysFieldBuilder() : null;
            } else {
              frageKeysBuilder_.addAllMessages(other.frageKeys_);
            }
          }
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsSplit()) {
          
          return false;
        }
        if (!hasLength()) {
          
          return false;
        }
        for (int i = 0; i < getFrageKeysCount(); i++) {
          if (!getFrageKeys(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mm.photo.proto.Storage.ImageFragInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mm.photo.proto.Storage.ImageFragInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool isSplit = 1 [default = false];
      private boolean isSplit_ ;
      /**
       * <code>required bool isSplit = 1 [default = false];</code>
       */
      public boolean hasIsSplit() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool isSplit = 1 [default = false];</code>
       */
      public boolean getIsSplit() {
        return isSplit_;
      }
      /**
       * <code>required bool isSplit = 1 [default = false];</code>
       */
      public Builder setIsSplit(boolean value) {
        bitField0_ |= 0x00000001;
        isSplit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isSplit = 1 [default = false];</code>
       */
      public Builder clearIsSplit() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isSplit_ = false;
        onChanged();
        return this;
      }

      // repeated .com.mm.photo.proto.ImageKey frageKeys = 2;
      private java.util.List<com.mm.photo.proto.Storage.ImageKey> frageKeys_ =
        java.util.Collections.emptyList();
      private void ensureFrageKeysIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          frageKeys_ = new java.util.ArrayList<com.mm.photo.proto.Storage.ImageKey>(frageKeys_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.mm.photo.proto.Storage.ImageKey, com.mm.photo.proto.Storage.ImageKey.Builder, com.mm.photo.proto.Storage.ImageKeyOrBuilder> frageKeysBuilder_;

      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public java.util.List<com.mm.photo.proto.Storage.ImageKey> getFrageKeysList() {
        if (frageKeysBuilder_ == null) {
          return java.util.Collections.unmodifiableList(frageKeys_);
        } else {
          return frageKeysBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public int getFrageKeysCount() {
        if (frageKeysBuilder_ == null) {
          return frageKeys_.size();
        } else {
          return frageKeysBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public com.mm.photo.proto.Storage.ImageKey getFrageKeys(int index) {
        if (frageKeysBuilder_ == null) {
          return frageKeys_.get(index);
        } else {
          return frageKeysBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public Builder setFrageKeys(
          int index, com.mm.photo.proto.Storage.ImageKey value) {
        if (frageKeysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFrageKeysIsMutable();
          frageKeys_.set(index, value);
          onChanged();
        } else {
          frageKeysBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public Builder setFrageKeys(
          int index, com.mm.photo.proto.Storage.ImageKey.Builder builderForValue) {
        if (frageKeysBuilder_ == null) {
          ensureFrageKeysIsMutable();
          frageKeys_.set(index, builderForValue.build());
          onChanged();
        } else {
          frageKeysBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public Builder addFrageKeys(com.mm.photo.proto.Storage.ImageKey value) {
        if (frageKeysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFrageKeysIsMutable();
          frageKeys_.add(value);
          onChanged();
        } else {
          frageKeysBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public Builder addFrageKeys(
          int index, com.mm.photo.proto.Storage.ImageKey value) {
        if (frageKeysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFrageKeysIsMutable();
          frageKeys_.add(index, value);
          onChanged();
        } else {
          frageKeysBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public Builder addFrageKeys(
          com.mm.photo.proto.Storage.ImageKey.Builder builderForValue) {
        if (frageKeysBuilder_ == null) {
          ensureFrageKeysIsMutable();
          frageKeys_.add(builderForValue.build());
          onChanged();
        } else {
          frageKeysBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public Builder addFrageKeys(
          int index, com.mm.photo.proto.Storage.ImageKey.Builder builderForValue) {
        if (frageKeysBuilder_ == null) {
          ensureFrageKeysIsMutable();
          frageKeys_.add(index, builderForValue.build());
          onChanged();
        } else {
          frageKeysBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public Builder addAllFrageKeys(
          java.lang.Iterable<? extends com.mm.photo.proto.Storage.ImageKey> values) {
        if (frageKeysBuilder_ == null) {
          ensureFrageKeysIsMutable();
          super.addAll(values, frageKeys_);
          onChanged();
        } else {
          frageKeysBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public Builder clearFrageKeys() {
        if (frageKeysBuilder_ == null) {
          frageKeys_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          frageKeysBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public Builder removeFrageKeys(int index) {
        if (frageKeysBuilder_ == null) {
          ensureFrageKeysIsMutable();
          frageKeys_.remove(index);
          onChanged();
        } else {
          frageKeysBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public com.mm.photo.proto.Storage.ImageKey.Builder getFrageKeysBuilder(
          int index) {
        return getFrageKeysFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public com.mm.photo.proto.Storage.ImageKeyOrBuilder getFrageKeysOrBuilder(
          int index) {
        if (frageKeysBuilder_ == null) {
          return frageKeys_.get(index);  } else {
          return frageKeysBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public java.util.List<? extends com.mm.photo.proto.Storage.ImageKeyOrBuilder> 
           getFrageKeysOrBuilderList() {
        if (frageKeysBuilder_ != null) {
          return frageKeysBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(frageKeys_);
        }
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public com.mm.photo.proto.Storage.ImageKey.Builder addFrageKeysBuilder() {
        return getFrageKeysFieldBuilder().addBuilder(
            com.mm.photo.proto.Storage.ImageKey.getDefaultInstance());
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public com.mm.photo.proto.Storage.ImageKey.Builder addFrageKeysBuilder(
          int index) {
        return getFrageKeysFieldBuilder().addBuilder(
            index, com.mm.photo.proto.Storage.ImageKey.getDefaultInstance());
      }
      /**
       * <code>repeated .com.mm.photo.proto.ImageKey frageKeys = 2;</code>
       */
      public java.util.List<com.mm.photo.proto.Storage.ImageKey.Builder> 
           getFrageKeysBuilderList() {
        return getFrageKeysFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mm.photo.proto.Storage.ImageKey, com.mm.photo.proto.Storage.ImageKey.Builder, com.mm.photo.proto.Storage.ImageKeyOrBuilder> 
          getFrageKeysFieldBuilder() {
        if (frageKeysBuilder_ == null) {
          frageKeysBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.mm.photo.proto.Storage.ImageKey, com.mm.photo.proto.Storage.ImageKey.Builder, com.mm.photo.proto.Storage.ImageKeyOrBuilder>(
                  frageKeys_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          frageKeys_ = null;
        }
        return frageKeysBuilder_;
      }

      // optional bytes data = 3;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 3;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 3;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // required int64 length = 4;
      private long length_ ;
      /**
       * <code>required int64 length = 4;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 length = 4;</code>
       */
      public long getLength() {
        return length_;
      }
      /**
       * <code>required int64 length = 4;</code>
       */
      public Builder setLength(long value) {
        bitField0_ |= 0x00000008;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 length = 4;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000008);
        length_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mm.photo.proto.ImageFragInfo)
    }

    static {
      defaultInstance = new ImageFragInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mm.photo.proto.ImageFragInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mm_photo_proto_ImageKey_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mm_photo_proto_ImageKey_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mm_photo_proto_ImageFragInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mm_photo_proto_ImageFragInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstorage.proto\022\022com.mm.photo.proto\"\027\n\010I" +
      "mageKey\022\013\n\003url\030\001 \002(\t\"v\n\rImageFragInfo\022\026\n" +
      "\007isSplit\030\001 \002(\010:\005false\022/\n\tfrageKeys\030\002 \003(\013" +
      "2\034.com.mm.photo.proto.ImageKey\022\014\n\004data\030\003" +
      " \001(\014\022\016\n\006length\030\004 \002(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mm_photo_proto_ImageKey_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mm_photo_proto_ImageKey_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mm_photo_proto_ImageKey_descriptor,
              new java.lang.String[] { "Url", });
          internal_static_com_mm_photo_proto_ImageFragInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_mm_photo_proto_ImageFragInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mm_photo_proto_ImageFragInfo_descriptor,
              new java.lang.String[] { "IsSplit", "FrageKeys", "Data", "Length", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
